reaviz/reaviz

src/PieChart/PieArcSeries/PieArcLabel.tsx, src/PieChart/PieArcSeries/PieArcSeries.tsx, src/PieChart/PieChart.story.tsx
```
[x] Bugfix
[ ] Feature
```
Current label polyline coords calculation algorithm may produce odd results in some cases.
The lines may  have completely wrong direction:
In other cases the lines have such trajectory, that it is difficult to understand exactly to which section the line points to:
In this PR I have added an alternative algorithm for the case, when label position is lower, than pie chart outer radius centroid. So now we have two ways to …
=> Improve polyline coords calculation for PieArcLabel

src/PieChart/PieArcSeries/PieArcLabel.test.tsx, src/PieChart/PieArcSeries/PieArcLabel.tsx, src/PieChart/PieArcSeries/PieArcSeries.tsx, src/PieChart/PieChart.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeArc.tsx
```
[x] Bugfix
[ ] Feature
```
I've introduced `import type` syntax in #10 which is supported in typescript 3.8+. This PR reverts that change to support users with older typescript version
```
[ ] Yes
[x] No
```
=> fix: revert typescript 3.8 "import type" syntax usage to allow support typescript < 3.7

docs/charts/RadialGauge.story.mdx, package.json, src/PieChart/PieArcSeries/PieArc.tsx, src/PieChart/PieArcSeries/PieArcLabel.tsx, src/PieChart/PieArcSeries/PieArcSeries.tsx, src/PieChart/PieArcSeries/useInterpolate.ts, src/PieChart/PieChart.story.tsx, src/PieChart/PieChart.tsx, src/RadialGauge/RadialGauge.story.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeArc.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeLabel.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeSeries.tsx, src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeSeries.tsx, src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisTick.tsx
Adding padAngle, padRadius and cornerRadius to the Arcs to use the full potential of the d3 arc generator
renaming the innerArc prop on PieArcProps as it is misleading (breaking change)
Add new story to show the usage
PieChart to FC
**Do not merge**
```
[ ] Bugfix
[x] Feature
```
Corner radius
padAngle + padRadius + corner radius
Full Arc features: https://github.com/d3/d3-shape#arcs
```
[x] Yes possibly
[ ] No
```
This is only a discussion right now, …
=> Better arcs

src/Heatmap/CalendarHeatmap.tsx
```
[x] Bugfix
[ ] Feature
```
`<CalendarHeatmap />` `series` prop is not passed into `<Heatmap />`, including the one from defaultProps, custom element does not render correctly, see the tooltip of storybook:
Storybook: https://reaviz.io/?path=/story/charts-heatmap-calendar--year-calendar
`series` is passing through rest props, the tooltip is showing correctly:
```
[ ] Yes
[x] No
```
=> Fix CalendarHeatmap series prop not passed into Heatmap

CHANGELOG.md, package.json, src/Map/Map.story.tsx, src/Map/Map.tsx
```
[ ] Bugfix
[X] Feature
```
Issue Number: #90 
- Adds [`geoNaturalEarth` projection](https://github.com/d3/d3-geo#geoNaturalEarth1) from `d3-geo` to the `Map` component that can be used by passing `projection="natural-earth"` prop into `Map`.
```
[ ] Yes
[X] No
```
**Docs Update**
**Storybook Story**
=> Add natural-earth projection to Map visualization

src/common/Brush/Brush.tsx
```
[x] Bugfix
[ ] Feature
```
Disabled brush (ie, if the histogram chart only has 1 bar) and user clicks on the bar and drags, it will crash
Underlying problem is that `ref` is undefined when disabled, so I'm adding a <rect /> with a ref to fix the issue.
```
[ ] Yes
[x] No
```
=> fix disabled brush crashing when clicking on bar

src/common/Brush/Brush.tsx
```
[x] Bugfix
[ ] Feature
```
Previously, even though I added a ref to an element, it would still cause the domain to update despite the brush being disabled.
onMoveStart and onMove is ignored so domain will not change
```
[ ] Yes
[ ] No
```
=> ignore onMoveStart and onMove if brush is disabled

src/common/Gridline/GridlineSeries.tsx
```
[x] Bugfix
[ ] Feature
```
Scatter Plot Grid Lines missing stripe
Issue Number: [102](https://github.com/reaviz/reaviz/issues/102)
Avoid skipping first stripe for Scatter Plot Grid Lines
```
[ ] Yes
[x] No
```
@amcdnl if you remember why this skip functionality was added - let me know
=> Avoid skip first index on scatter plot grid rendering

src/BarList/BarList.story.tsx, src/BarList/BarList.tsx
This PR adds support for percentage values in the BarList component. Earlier all the bars were relative so even if the inputs were percentages and the max input was less than 100, it would still show a full bar.
```
[ ] Bugfix
[x] Feature
```
Incorrectly renders percentage value bars.
Correctly renders percentage value bars.
```
[ ] Yes
[x] No
```
=> Barlist: support for percentage values

src/TreeMap/TreeMapLabel.tsx
Calculate label width based on nowrap value.
```
[X] Bugfix
```
If the user sets nowrap to false, the width is calculated based on the whole text instead of just what will be presented on the screen. This causes the text to display outside of the box when placement is set to middle
Center text when placement is set to middle and nowrap set to false
```
[ ] Yes
[X] No
```
**Solution:**
=> Calculate TreeMapLabel width based on nowrap value

src/TreeMap/TreeMapLabel.tsx
Update value being passed to calculateDimensions from treeMapLabel
```
[X] Bugfix
```
If wrap is set to false but the text is too short and doesn't go through the wrap text logic, it doesn't center as expected.
Center text when wrap is set to false but the text is too short to require wrapping
```
[ ] Yes
[X] No
```
The only scenario that ```wrapText``` returns a plain string is when wrap is set to false and the text is long.
**Solution:**
=> TreepMapLabel: Update nowrap label width

src/RadialAreaChart/RadialAreaChart.story.tsx, src/RadialAreaChart/RadialAreaChart.tsx, src/RadialAreaChart/RadialAreaSeries/RadialArea.tsx, src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx, src/RadialAreaChart/RadialAreaSeries/RadialLine.tsx, src/RadialAreaChart/RadialLineChart.story.tsx, src/common/Axis/RadialAxis/RadialAxis.tsx, src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArc.tsx, src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArcSeries.tsx, src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTick.tsx, src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLabel.tsx, src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickSeries.tsx, src/common/Gradient/RadialGradient.story.tsx, src/common/Tooltip/TooltipArea.tsx, src/common/utils/position.ts
```
[ ] Bugfix
[x] Feature
```
Currently the radial chart only renders a complete circle.
It now supports rendering a radial chart of any dimension(sector) by setting the newly added `startAngle` and `endAngle` properties. The chart is rendered from  the `startAngle` to the `endAngle` in the **clockwise direction**.
Additionally, a `isClosedCurve` property has been added if closed interpolation of line/area curve is not required (which may be required …
=> Generic Radial chart for all start and end angles with open/closed curve options

src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickSeries.tsx
This PR adds support for a callback function with index in addition to the existing fixed element for a `tick` value.
This is mostly useful in scenarios where the line styles and labels would vary depending upon where they lie (start/end/middle/alternate ticks, etc.) on the chart so we can customise their positioning (inside/outside) or even the labels associated with them.
=> Radial Axis Tick Series: Callback with index for tick element

src/FunnelChart/FunnelChart.story.tsx, src/FunnelChart/FunnelSeries/FunnelAxis/FunnelAxisLabel.tsx
```
[ ] Bugfix
[x] Feature
```
Currently you cannot change a Funnel Chart's label position, prevent the label from hiding when the width is too great, or hide the value of the segment data in the label
Issue Number: [GOOD-85](https://linear.app/goodcodeus/issue/GOOD-85/update-funnelchart-labels)
Now you can:
- Change a label's position to `top`, `center`, or `bottom`
- Always show the label
- Hide the value of a segment's data in the label
```
[ ] Yes
[x] No
```
=> GOOD-85: Add positioning and conditional display to FunnelChart labels

src/FunnelChart/FunnelSeries/FunnelAxis/FunnelAxisLabel.tsx, src/common/utils/wrapText.tsx
```
[x] Bugfix
[ ] Feature
```
Using a FunnelChart label that is very long causes the UI to crash. This is because at a certain input length the `wrapText()` util returns `null` instead of a `tspan`
Using very long FunnelChart labels won't crash the UI. I also added the option to always return the wrapped text from `wrapText()` regardless of the length
```
[ ] Yes
[ ] No
```
=> Bugfix/long FunnelChart labels crashing UI

demo/category.ts, src/RadialGauge/RadialGauge.story.tsx, src/RadialGauge/RadialGauge.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeArc.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeSeries.tsx, src/RadialGauge/RadialGaugeSeries/RadialGaugeStackedArc.tsx, src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeDescriptionLabel/StackedRadialGaugeDescriptionLabel.tsx, src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeSeries.tsx, src/RadialGauge/RadialGaugeSeries/index.ts
```
[ ] Bugfix
[x] Feature
```
StackedRadialGaugeSeries doesn't have ability to build stacked arcs
Issue Number: #166 
RadialGauge have ability to process data with nested structure (ChartDataShape) and draw stacked arcs for nested data
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reaviz/assets/5399389/759b4f97-6332-462f-abad-fc999b4b6873
=> Feature/Add ability to build Stacked arcs for StackedRadialGaugeSeries

src/AreaChart/AreaSeries/Area.tsx, src/AreaChart/AreaSeries/AreaSeries.tsx, src/AreaChart/AreaSeries/Line.tsx, src/RadialAreaChart/RadialAreaSeries/RadialArea.tsx, src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx, src/RadialAreaChart/RadialAreaSeries/RadialLine.tsx, src/RadialBarChart/RadialBarSeries/MotionBar.tsx, src/RadialBarChart/RadialBarSeries/RadialBar.tsx, src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx, src/common/Motion/MotionPath.tsx
```
[x] Bugfix
[ ] Feature
```
Hovering your mouse over area charts and radial bar charts while they're in their initial animation causes the animation to restart constantly.
Chart animations for area charts and radial bar charts behave normally. Mark lines, points, active bars are no longer rendered during animations
```
[ ] Yes
[x] No
```
**BEFORE**
https://github.com/reaviz/reaviz/assets/40581813/199726fb-d1a1-40f3-84cd-aaee8eb444b7
**AFTER** …
=>  Fix animation restarting on hover

src/AreaChart/AreaSeries/Area.tsx, src/AreaChart/AreaSeries/AreaSeries.tsx, src/AreaChart/AreaSeries/Line.tsx, src/RadialAreaChart/RadialAreaSeries/RadialArea.tsx, src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx, src/RadialAreaChart/RadialAreaSeries/RadialLine.tsx, src/RadialBarChart/RadialBarSeries/MotionBar.tsx, src/RadialBarChart/RadialBarSeries/RadialBar.tsx, src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx, src/common/Motion/MotionPath.tsx
```
[x] Bugfix
[ ] Feature
```
When live updating data quickly, the chart data points look to be resetting to where they started at the previous animation before animating to the new position
Chart data points animate starting from where they were interrupted towards their new position
```
[ ] Yes
[x] No
```
**BEFORE**
https://github.com/reaviz/reaviz/assets/40581813/63aa5531-02b3-4c7e-8eb4-3942ab90dbed
**AFTER** …
=> Fix jittering chart animations when updating data quickly

package-lock.json, src/BubbleChart/BubbleLabel.tsx, src/BubbleChart/BubbleSeries.tsx
```
[x] Bugfix
[ ] Feature
```
- Bubble chart prop `fill` on `BubbleLabel` doesn't work
- `colorScheme` with gradients don't work
Bubbel Label fills and color schemes work as expected through
```
[ ] Yes
[x] No
```
BubbleLabel fill
BEFORE
AFTER
color schemes with gradients
BEFORE
AFTER
=> Fix some bubble chart styling props

docs/charts/Heatmap.mdx, src/Heatmap/HeatmapSeries/HeatmapCell.tsx, src/Heatmap/HeatmapSeries/HeatmapSeries.tsx, src/common/color/helper.ts
```
[ ] Bugfix
[x] Feature
```
There's limited styling options for heatmaps
You can now specify a `fill`, `stroke`, and `filter` in your heatmap color scheme
```
[ ] Yes
[x] No
```
This adds a new optional shape for `colorScheme` that can be used in `HeatmapSeries`. 
e.g.
```
colorScheme: { fill: string, stroke: string, filter: string}
```
This is a color scheme type that could be useful in other graphs where you want to include more properties in your color scheme …
=> Add stroke and glow to Heatmaps

src/AreaChart/AreaChartCircle.story.tsx, src/LineChart/LineChartCircle.story.tsx, src/RadialBarChart/RadialBarSeries/MotionBar.tsx, src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.module.css, src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.module.css.d.ts, src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx, src/RadialScatterPlot/RadialScatterSeries/RadialScatterSeries.tsx, src/ScatterPlot/ScatterSeries/ScatterPoint.module.css, src/ScatterPlot/ScatterSeries/ScatterPoint.module.css.d.ts, src/ScatterPlot/ScatterSeries/ScatterPoint.tsx, src/ScatterPlot/ScatterSeries/ScatterSeries.tsx
This PR enables tabbing through the data points even when the symbols are not visible as we now render the points and set their opacity to 0 instead of removing them from the DOM.
https://github.com/reaviz/reaviz/assets/33908100/c5c0e979-959a-4247-aa7e-890078581f0c
=> UNF-100: Line/Area/Radial - hide points instead of removing from DOM - enable tabbing

package-lock.json, src/BarChart/BarSeries/BarSeries.tsx, src/FunnelChart/FunnelSeries/FunnelSeries.tsx, src/common/Tooltip/TooltipArea.tsx, src/common/utils/position.test.ts, src/common/utils/position.ts
```
[x] Bugfix
[ ] Feature
```
Tooltips aren't accurate on bar charts using continuous x scales. It shows the tooltip for the next data point halfway through the one you're hovering
The correct tooltip shows for the bar you are hovering over
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reaviz/assets/40581813/4444685a-c015-42eb-b63e-2ad39c9bbfbe
AFTER
https://github.com/reaviz/reaviz/assets/40581813/9a9f2cd2-b367-4100-b643-a425c4fd1092
=> Fix bar chart tooltip hover accuracy

src/AreaChart/AreaSeries/Area.tsx
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improvement
```
Multi-series area charts can only glow one color
If you don't specify an area glow color, it will use the stroke color which is based off the color scheme
```
[ ] Yes
[x] No
```
If a glow color's not specified, this will use the color of the area stroke
This allows multiseries data to glow different colors based off the color scheme
=> Improve multi-series area chart glow

src/Heatmap/HeatmapSeries/HeatmapSeries.tsx
```
[x] Bugfix
[ ] Feature
```
Heatmap cell styling is limited even though the type on `colorScheme` implies you can pass any style you want
You can pass any style in `colorScheme` and it reflects in heatmap cells
```
[ ] Yes
[x] No
```
e.g. I want to pass a `colorScheme` with styling like `strokeWidth`
```
colorScheme={[
{ fill: '#9152EE40', stroke: '#9152EE', strokeWidth: '2px' }
{ fill: '#9152EE' },
{ fill: '#F8A340' },
{ fill: '#FFD440', filter: 'drop-shadow(0px …
```
=> Fix heatmap cell styling

src/Heatmap/calendarUtils.ts
```
[x] Bugfix
[ ] Feature
```
Including 365 days of data to `HeatmapCalendar` doesn't display all the data
Issue Number: #237 
365 days of data (starting 364 days from most recent) is displayed in `HeatmapCalendar`
```
[ ] Yes
[x] No
```
This was happening because the `year` view on `HeatmapCalendar` is restricted to 52 weeks while also transforming the start date to the first of the month of the earliest piece of data. This means some data towards the end of the date …
=> Fix HeatmapCalendar not showing all data

package-lock.json, package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: chore
```
This updates @upsetjs/venn.js to the newest version to fix a vulnerability
```
[ ] Yes
[x] No
```
The vuln that was fixed:
```
rollup  <2.79.2
Severity: high
DOM Clobbering Gadget found in rollup bundled scripts that leads to XSS - https://github.com/advisories/GHSA-gcx4-mw62-g8wm
fix available via `npm audit fix --force`
Will install @upsetjs/venn.js@2.0.0, which is a breaking change
node_modules/fmin/node_modules/rollup
fmin …
```
=> Update venn.js dependency
