.storybook/main.js

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
There's currently no `remark-codesandbox` set up for Storybook Docs.
Set up `remark-codesandbox` for Storybook Docs.
```
[ ] Yes
[x] No
```
See https://github.com/kevin940726/remark-codesandbox/issues/14

Integrate remark-codesandbox with Storybook Docs

---

src/VennDiagram/README.md
src/VennDiagram/VennDiagram.story.tsx
src/VennDiagram/VennDiagram.tsx
src/VennDiagram/VennLabel.tsx
src/VennDiagram/VennSeries.tsx
src/VennDiagram/data/venn0.json
src/VennDiagram/data/venn1.json
src/VennDiagram/data/venn2.json
src/VennDiagram/data/venn3.json
src/VennDiagram/data/venn4.json
src/VennDiagram/data/venn5.json
src/VennDiagram/starEuler.ts

Star Euler

---

package.json
src/PieChart/PieArcSeries/PieArcLabel.tsx
src/PieChart/PieArcSeries/PieArcSeries.tsx
src/PieChart/PieArcSeries/findBreakPoint.test.ts
src/PieChart/PieArcSeries/findBreakPoint.ts
yarn.lock

```
[x] Bugfix
[ ] Feature
```
This PR fixes a bug introduced in #12 which have caused label lines to be shown inside of donut:
The labels should be rendered correctly. I've also a little bit covered label line coords calculation with tests
```
[ ] Yes
[x] No
```

Fix pie chart label lines

---

.gitignore
src/RadialGauge/RadialGauge.story.tsx
src/RadialGauge/RadialGauge.tsx
src/RadialGauge/RadialGaugeSeries/RadialGaugeSeries.tsx
src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeLabel.tsx
src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeSeries.tsx
src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeValueLabel.module.scss

```
[ ] Bugfix
[x] Feature
```
Issue Number: See #17 
```
[ ] Yes
[x] No
```

Feature StackedRadialGauge

---

.gitignore
src/RadialGauge/RadialGauge.tsx
src/RadialGauge/RadialGaugeSeries/RadialGaugeSeries.tsx

Converting RadialGauge and RadialGaugeSeries to Functional components
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #13
Should behave the same
```
[ ] Yes
[x] No
```

Converting RadialGauge and RadialGaugeSeries to Functional Componen

---

src/AreaChart/AreaSeries/Line.tsx

```
[x] Bugfix
[ ] Feature
```
Issue Number: #21 
```
[ ] Yes
[x] No
```

fix: arechart lines rendered incorreclty when changing brush selection

---

src/Heatmap/CalendarHeatmap.tsx
src/Heatmap/Heatmap.tsx
src/Heatmap/HeatmapSeries/HeatmapCell.module.css.d.ts
src/Heatmap/HeatmapSeries/HeatmapCell.tsx
src/Heatmap/HeatmapSeries/HeatmapSeries.tsx
src/Heatmap/calendarUtils.ts
src/common/ZoomPan/ZoomPan.story.tsx

```
[ ] Bugfix
[ ] Feature
[ X] Refactoring (no functional changes, no api changes)
```
Convert Heatmap folder to be functional components.
```
[ ] Yes
[ X] No
```
@amcdnl I need some help with `HeatmapSeries`, I am getting strange behavior and cannot locate the issue. 
would appreciate your help with that.
```
const xScale = scaleBand()
.range([0, chartWidth])
.domain(xDomain)
.paddingInner(series.props.padding);
```
on the new FC, xScale range is set to a map of key to NaN.

Heatmap to fc

---

src/HivePlot/HiveAxis/HiveAxis.tsx
src/HivePlot/HiveLabel/HiveLabel.tsx
src/HivePlot/HiveLink/HiveLink.tsx
src/HivePlot/HiveNode/HiveNode.tsx
src/HivePlot/HivePlot.story.tsx
src/HivePlot/HivePlot.tsx
src/HivePlot/HiveTooltip/HiveTooltip.tsx
src/common/containers/ChartContainer.tsx

Convert Hiveplot dir to functional component

Fc hiveplot

---

src/AreaChart/AreaSeries/Area.tsx
src/AreaChart/AreaSeries/AreaSeries.tsx
src/AreaChart/AreaSeries/Line.tsx
src/AreaChart/AreaSeries/PointSeries.tsx

Revert "Yohay/area serias fc"

---

src/common/Axis/LinearAxis/LinearAxisLine.tsx

- [X ] Tests for the changes have been added (for bug fixes / features)
```
[X ] Bugfix
[ ] Feature
```
Issue Number: #67 
strokeWidth number will be used as line element stroke-width.
```
[ ] Yes
[X ] No
```

use strokeWidth prop for line element

---

src/AreaChart/AreaSeries/Area.tsx
src/AreaChart/AreaSeries/AreaSeries.tsx

Before:
After:
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Area graph with single value fills available area

---

src/common/utils/position.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #28
```
[ ] Yes
[x] No
```

fix transform-matrix nested type build error 

---

src/common/Brush/Brush.story.tsx
src/common/Brush/ChartBrush.tsx

```
[x] Bugfix
[ ] Feature
```
BarChart using `category` type xAxis is blowing up when `onBrushChange` is called due to scale not having the invert function
I basically wrote a scale bend invert function to handle reversing the scaleBend when an invert function does not exist on the scale object.
```
[ ] Yes
[x] No - at least I don't think so?
```
I'm not 100% sure this doesn't break something else lol

Update scale for BarChart brush

---

src/common/containers/ChartContainer.tsx

```
[x] Bugfix
[ ] Feature
```
Chart container had an unexpected x offset
No more unexpected offset! The useState hook for x and y offsets were mixed around lol
```
[ ] Yes
[x] No - don't think so?
```

Fix the x and y offset for chartContainer

---

package.json

Fix esm import

---

src/TreeMap/TreeMap.story.tsx
src/common/utils/wrapText.tsx

```
[x] Bugfix
[ ] Feature
```
Issue Number: #75
`wrapText` now works with treemap. There is a new story of a treemap with long label texts.
```
[ ] Yes
[x] No
```

Edited wrapText() and added a treemap example with long label texts

---

src/VennDiagram/VennDiagram.story.tsx
src/VennDiagram/VennSeries.tsx

```
[x] Bugfix
[ ] Feature
```
A label is visible for VennSeries if `null` value passed
Issue Number: [66](https://github.com/reaviz/reaviz/issues/66)
A label is hidden for VennSeries if `null` value passed
```
[ ] Yes
[x] No
```

Hide label if `null` value passed for VennSeries

---

src/AreaChart/AreaSeries/AreaSeries.tsx

Bug fix
```
[x] Bugfix
[ ] Feature
```
On hover, the tooltip area does not show the colors.
Issue Number: https://github.com/reaviz/reaviz/issues/101
On hover, the tooltip area shows the colors as well.
```
[ ] Yes
[x] No
```

Fixed: Tooltip missing colors in Line/Area Series

---

src/BarList/BarList.story.tsx
src/BarList/BarList.tsx

Fixes issue with All zero values in bar list
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Fix: Bar List All zeros

---

src/Heatmap/calendarUtils.ts

```
[x] Bugfix
[ ] Feature
```
The calendar heatmap crashes when input source is an empty list
The calendar heatmap shows empty blocks even with empty list input
```
[ ] Yes
[x] No
```

Fix: CalendarHeatMap crashing with empty data

---

src/TreeMap/TreeMap.story.tsx
src/TreeMap/TreeMap.tsx
src/TreeMap/TreeMapRect.tsx

```
[ ] Bugfix
[x] Feature
```
Nested Tree map was not supported
Nested Tree map is supported
https://user-images.githubusercontent.com/33908100/235328194-32c477cb-6b39-494b-9075-3c094f121c2c.mov
```
[ ] Yes
[x] No
```

Feature: Nested Tree map

---

docs/charts/RadialGauge.story.mdx

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Docs currently reference the wrong files, which results in the correct documentation not being displayed in storybook.
Fixed the file names so that the correct documentation is displayed.
```
[ ] Yes
[x] No
```

bug: fix the names for radial gauge label docs

---

src/AreaChart/AreaChartMultiSeries.story.tsx
src/AreaChart/AreaChartSingleSeries.story.tsx
src/BarChart/BarChartVerticalMultiSeries.story.tsx
src/BubbleChart/BubbleChart.story.tsx
src/Heatmap/Heatmap.story.tsx
src/LineChart/LineChartMultiSeries.story.tsx
src/LineChart/LineChartSingleSeries.story.tsx
src/PieChart/DonutChart.story.tsx
src/PieChart/PieChart.story.tsx
src/RadialAreaChart/RadialAreaChart.story.tsx
src/RadialAreaChart/RadialLineChart.story.tsx
src/RadialBarChart/RadialBarChart.story.tsx
src/RadialGauge/RadialGauge.story.tsx
src/RadialScatterPlot/RadialScatterPlot.story.tsx
src/Sankey/Sankey.story.tsx

```
[ ] Bugfix
[ ] Feature
```
Storybook code refactor
```
[ ] Yes
[X] No
```

GOOD-42: Remove storybook knobs

---

package.json
src/AreaChart/AreaChartMultiSeries.story.tsx
yarn.lock

Remove storybook knobs package
```
[ ] Bugfix
[ ] Feature
```
NA
NA
Remove storybook knobs package
```
[ ] Yes
[X] No
```

Remove storybook knobs package

---

src/LineChart/LineChartMultiSeries.story.tsx

This PR adds a story for enabling click on Multiline Charts since the click behavior might be a common use case so it would be good to have an example with the suitable props.
https://github.com/reaviz/reaviz/assets/33908100/1eb30335-2360-4f1c-81f3-907de2c398d1

Added story for multiline chart click

---

.prettierrc
CHANGELOG.md
src/common/Axis/LinearAxis/LinearAxis.story.tsx
src/common/Axis/LinearAxis/LinearAxis.tsx
src/common/Axis/LinearAxis/LinearAxisLine.tsx
src/common/Axis/LinearAxis/LinearAxisTickLabel.tsx
src/common/Axis/LinearAxis/LinearAxisTickLine.tsx
src/common/Axis/LinearAxis/LinearAxisTickSeries.tsx
src/common/Axis/LinearAxis/LinearXAxis.tsx
src/common/Axis/LinearAxis/LinearYAxis.tsx

```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
```
Convert the LinearAxis component and all subcomponents from class-based to functional components. 
Behavior should be unchanged. 
```
[ ] Yes
[X] No
```

Convert LinearAxis to Functional Components

---

src/BarChart/BarSeries/BarSeries.tsx
src/common/Axis/LinearAxis/LinearAxisTickLine.tsx
src/common/Axis/LinearAxis/LinearAxisTickSeries.tsx
src/common/Brush/Brush.tsx
src/common/Brush/BrushHandle.tsx
src/common/Brush/BrushSlice.tsx
src/common/Brush/ChartBrush.tsx
src/common/Tooltip/TooltipArea.tsx
src/common/ZoomPan/ChartZoomPan.tsx
src/common/ZoomPan/ZoomPan.tsx
src/common/legends/DiscreteLegend/DiscreteLegendEntry.tsx
src/common/legends/SequentialLegend/SequentialLegend.tsx

```
[ ] Bugfix
[ ] Feature
```
Issue Number: GOOD-44
```
[ ] Yes
[x] No
```
List of converted components:
* ChartBrush
* BrushSlice
* BrushHandle
* Brush
* ZoomPan
* SequentialLegend
* TooltipArea
* LinearAxisTickSeries
* LinearAxisTickLine

Functional components

---

src/common/Axis/LinearAxis/LinearAxisTickLabel.tsx

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

Fix padding

---

src/RadialBarChart/RadialAxisBarChart.story.tsx
src/RadialBarChart/RadialBarChart.tsx
src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx

This PR adds support for custom angles in Radial Bar charts.
https://github.com/reaviz/reaviz/assets/33908100/1db6c652-73c9-47aa-9b4e-040b8a2a8611

Custom angles in Radial Bar Chart

---

src/RadialBarChart/RadialAxisBarChart.story.tsx
src/RadialBarChart/RadialBarChart.story.tsx
src/RadialBarChart/RadialBarChart.tsx
src/RadialBarChart/RadialBarSeries/RadialBar.tsx
src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx
src/common/Tooltip/TooltipArea.tsx
src/common/utils/position.ts

This PR adds multiseries support for Radial Bar charts (including all angles).
https://github.com/reaviz/reaviz/assets/33908100/5a307b68-321c-4248-af3f-c2cb92823f02

Multiseries support in Radial Bar Charts

---

src/BarChart/BarSeries/Bar.tsx
src/BarChart/BarSeries/BarSeries.tsx
src/FunnelChart/FunnelArc.tsx
src/FunnelChart/FunnelChart.story.tsx
src/FunnelChart/FunnelChart.tsx
src/common/Tooltip/TooltipArea.tsx
src/common/containers/ChartContainer.tsx
src/common/types.ts
src/common/utils/position.ts

```
[ ] Bugfix
[x] Feature
```
Currently Funnel Charts don't support tooltips or an onClick handler to return relevant data
Issue Number: [GOOD-76](https://linear.app/goodcodeus/issue/GOOD-76/add-tooltip-and-click-handler-to-funnel-charts)
Funnel Charts now support tooltips on hover and an onClick handler to return relevant data
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reaviz/assets/40581813/fc1aa4d7-215b-458f-9ab9-3fbb23507c22

Add tooltip and click handler to Funnel Charts

---

src/BarChart/BarChartVertical.story.tsx
src/RadialBarChart/RadialBarChart.story.tsx
src/RadialBarChart/RadialBarChart.tsx
src/RadialBarChart/RadialBarSeries/MotionBar.tsx
src/common/Motion/MotionPath.tsx

This PR:
- Fixes animations on linear area chart
- Fixes animations on radial area chart
- Fixes animations on radial bar chart

Animation Fixes

---

src/RadialBarChart/RadialBarChart.tsx
src/common/Tooltip/TooltipArea.tsx

Also updated a dependency list in `TooltipArea`.

Radial Bar chart: increased default inner radius

---

src/FunnelChart/FunnelChart.story.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx

```
[x] Bugfix
[ ] Feature
```
Currently FunnelSeries `onSegmentClick()` only works if you are also using a tooltip
FunnelSeries `onSegmentClick()` now works with or without a tooltip
```
[ ] Yes
[x] No
```

Get FunnelChart click to work without a tooltip

---

docs/utils/Legends.mdx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix docs for sequentiallegend

---

src/Map/Map.tsx

```
[ ] Bugfix
[x] Feature
```
Unable to import MapProps
Can now import MapProps
```
[ ] Yes
[x] No
```

Export MapProps

---

src/Meter/Meter.story.tsx
src/Meter/MeterColumn.tsx

```
[x] Bugfix
[ ] Feature
```
`min` and `max` props don't have any effect on the Meter
Issue Number: https://github.com/reaviz/reaviz/issues/130
Fixes the above issue
```
[ ] Yes
[x] No
```
Resolves https://github.com/reaviz/reaviz/issues/130

Fix: Meter min/max not working

---

src/RadialGauge/RadialGauge.story.tsx
src/RadialGauge/RadialGauge.tsx
src/RadialGauge/RadialGaugeSeries/StackedRadialGaugeSeries.tsx

```
[ ] Bugfix
[x] Feature
```
Currently we can set single MAX value for all series
Separate MAX value for each series
```
[ ] Yes
[x] No
```

RadialGauge min/max value array support

---

.storybook/preview.tsx
.storybook/utils/formatCode.ts
docs/utils/Glow.mdx
package-lock.json
package.json
src/BarChart/BarSeries/Bar.tsx
src/BubbleChart/Bubble.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx
src/ScatterPlot/ScatterSeries/ScatterPoint.tsx
src/common/Glow/Glow.story.tsx
src/common/Glow/Glow.tsx
src/common/Glow/utils.ts

```
[ ] Bugfix
[x] Feature
```
There's no option to pass a `glow` to funnel charts
You can now pass a `glow` element to FunnelArc
```
[ ] Yes
[x] No
```
New Glow docs
https://github.com/reaviz/reaviz/assets/40581813/6b8c5f47-75e7-455f-bd0b-f2454c0e9f86

Add funnel chart glow

---

src/BarChart/BarSeries/Bar.tsx
src/BubbleChart/Bubble.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx
src/ScatterPlot/ScatterSeries/ScatterPoint.tsx
src/VennDiagram/VennArc.tsx
src/VennDiagram/VennSeries.tsx
src/common/Glow/utils.ts

```
[ ] Bugfix
[x] Feature
```
There's no glow option for Venn Diagrams
You can now pass in a `glow` to `VennArc` 
```
[ ] Yes
[x] No
```
e.g.

Add venn diagram glow

---

src/VennDiagram/VennLabel.tsx
src/VennDiagram/VennSeries.tsx

```
[x] Bugfix
[ ] Feature
```
Passing in a custom `fill` to `VennLabel` doesn't do anything
Passing in custom `fill` to `VennLabel` sets the label color
```
[ ] Yes
[x] No
```
**BEFORE**
**AFTER**

Fix venn diagram label fill

---

package-lock.json
package.json
src/LineChart/LineChartSingleSeries.story.tsx
src/PieChart/PieArcSeries/PieArc.tsx
src/PieChart/PieArcSeries/useInterpolate.ts
src/RadialBarChart/RadialBarSeries/MotionBar.tsx
src/RadialBarChart/RadialBarSeries/RadialBar.tsx
src/VennDiagram/useInterpolate.ts
src/common/Motion/MotionPath.tsx

This PR:
- Upgrades framer-motion
- Refactors useInterpolate to work with latest framer-motion

Upgrade Framer Motion

---

src/PieChart/PieArcSeries/useInterpolate.ts
src/VennDiagram/useInterpolate.ts
src/common/Motion/MotionPath.tsx

```
[x] Bugfix
[ ] Feature
```
The setTimeout used to delay the initial animation on pie charts was causing the animation to be interrupted on rapid re-renders
Removed initial animation delay
```
[ ] Yes
[x] No
```
Also updated the deprecated `spring.onChange`

Fix pie chart animation

---

src/Heatmap/HeatmapCalendar.story.tsx
src/Heatmap/HeatmapSeries/HeatmapSeries.tsx
src/common/color/helper.ts

```
[ ] Bugfix
[x] Feature
```
Though `colorScheme` supports callback functions currently, but the params received there are undefined so it's unusable.
Can set color based on data/selected state of Heatmap.
https://github.com/reaviz/reaviz/assets/33908100/13bbd4f5-3e20-4430-83d6-489eb1c4f3ac
```
[ ] Yes
[x] No
```

Heatmap: Add colorScheme callback function support

---

src/BarChart/BarSeries/Bar.tsx
src/BarList/BarListSeries.tsx
src/BubbleChart/Bubble.tsx
src/Heatmap/HeatmapSeries/HeatmapCell.tsx
src/Map/MapMarker.tsx
src/PieChart/PieArcSeries/PieArc.tsx
src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx
src/Sankey/SankeyNode/SankeyNode.tsx
src/ScatterPlot/ScatterSeries/ScatterPoint.tsx
src/TreeMap/TreeMapRect.tsx
src/VennDiagram/VennArc.tsx

https://github.com/reaviz/reaviz/assets/33908100/e5e6caba-4b75-468b-967d-3128277f2a8e

UNF-100: Keyboard Navigation for Data Points on charts

---

package-lock.json
src/AreaChart/AreaSeries/Line.tsx
src/common/Gradient/LinearGradient.story.tsx

This PR adds the gradient prop for Line charts.

Gradient support for Line chart

---

src/AreaChart/AreaSeries/StackedNormalizedAreaSeries.tsx
src/BarChart/BarChart.tsx
src/BarChart/BarSeries/HistogramBarSeries.tsx
src/BarChart/BarSeries/StackedNormalizedBarSeries.tsx
src/RadialBarChart/RadialBarSeries/RadialBar.tsx
src/Sparkline/AreaSparklineChart.tsx
src/common/Gestures/Move.tsx

```
[ ] Bugfix
[ ] Feature
```
Refactoring
Issue Number:  GOOD-44
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reaviz/assets/11332713/df3615d0-702b-4d5d-aaa9-f7233c892520

good-44 refactor move component and cleanup

---

src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.module.css
src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx
src/RadialScatterPlot/RadialScatterSeries/RadialScatterSeries.tsx

```
[x] Bugfix
[ ] Feature
```
https://github.com/reaviz/reaviz/issues/188
Issue Number: [188](https://github.com/reaviz/reaviz/issues/188)
added opacity for inactive items instead hidding
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reaviz/assets/5399389/f03c8432-4dd5-422f-9646-745c3d4be9d5

Fix disappearing on hover

---

src/AreaChart/AreaChart.tsx
src/BarChart/BarChart.tsx
src/Heatmap/Heatmap.tsx
src/ScatterPlot/ScatterPlot.tsx
src/common/Axis/LinearAxis/LinearAxis.tsx

```
[x] Bugfix
[ ] Feature
```
Issue Number: [190](https://github.com/reaviz/reaviz/issues/190)
```
[ ] Yes
[x] No
```

Hide axis until chart became visible to avoid blinking

---

src/BubbleChart/BubbleChart.story.tsx
src/BubbleChart/BubbleSeries.tsx

```
[x] Bugfix
[ ] Feature
```
Bubble chart with icons doesn't work
Bubble chart with icons  work
```
[ ] Yes
[x] No
```
before:
after:

fix bubble chart with icons

---

src/BubbleChart/Bubble.tsx
src/BubbleChart/BubbleSeries.tsx

```
[ ] Bugfix
[x] Feature
```
There was no data from the bubble when you clicked on the bubble and there was no customization option for rendering
when you click on a bubble, you can get data and can customize the rendering
```
[ ] Yes
[x] No
```

added flexibility for bubble

---

src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLabel.tsx

```
[ ] Bugfix
[x] Feature
```
Doesn't have ability to pass all properties for text
Added ability to pass all properties for text
```
[ ] Yes
[x] No
```

Separate textProps for RadialAxisTickLabel text properties

---

docs/utils/Glow.mdx
src/AreaChart/AreaSeries/Area.tsx
src/common/Glow/Glow.story.tsx

```
[ ] Bugfix
[x] Feature
```
You can add glow to Area charts
```
[ ] Yes
[x] No
```

Add glow to area chart

---

docs/utils/Glow.mdx
src/AreaChart/AreaSeries/Line.tsx
src/common/Glow/Glow.story.tsx

```
[ ] Bugfix
[x] Feature
```
Lines can glow
```
[ ] Yes
[x] No
```

Add Line glow

---

src/Heatmap/Heatmap.story.tsx
src/Heatmap/HeatmapSeries/HeatmapCell.tsx

```
[ ] Bugfix
[x] Feature
```
There's no way to customize the shape of a heatmap cell
You can customize heatmap cells with the `symbol` prop
```
[ ] Yes
[x] No
```

Add custom symbols for heatmap cells

---

src/common/legends/SequentialLegend/SequentialLegend.tsx

```
[ ] Bugfix
[x] Feature
```
There's no way to customize the styling of the gradient element on the `SequentialLegend`
You can pass a class through the `gradientClassName` prop to customize the gradient element
```
[ ] Yes
[x] No
```
I just wanna make it a little narrower 😁

Add SequentialLegend gradient element styling

---

src/BarChart/BarSeries/Bar.tsx

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improvement
```
You can only specify one glow color for every bar in a bar chart
A Bar's glow color defaults to the current color in the color scheme when not specified
```
[ ] Yes
[x] No
```

Improve bar glow

---

src/AreaChart/AreaChartMarkers.story.tsx
src/AreaChart/AreaSeries/AreaSeries.tsx
src/BarChart/BarChartMarkers.story.tsx
src/LineChart/LineChartMarkers.story.tsx
src/ScatterPlot/ScatterPlotMarkers.story.tsx
src/ScatterPlot/ScatterSeries/ScatterSeries.tsx
src/common/ValueMarker/LinearValueMarker.tsx

```
[ ] Bugfix
[x] Feature
```
no opportunity to add vertical line to scatter plot
added and vertical line support for scatter plot 
```
[ ] Yes
[x] No
```

added vertical line support for charts

---

src/BarChart/BarChartVerticalHistogram.story.tsx
src/common/Axis/LinearAxis/LinearAxisTickLabel.tsx

Improve tick alignment

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: chore
```
```
[ ] Yes
[z] No
```

Upgrade to reablocks v7

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: chore
```

Upgrade reablocks

---

src/common/Axis/LinearAxis/LinearAxisTickLabel.tsx
src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLabel.tsx

```
[ ] Bugfix
[x] Feature
```
no opportunity format title on hover label
add format title on hover label
```
[ ] Yes
[x] No
```

add format title on hover label

---

CHANGELOG.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Fix changelog to render as MDX

---

package-lock.json
package.json
src/BarChart/BarChartHorizontal.story.tsx
src/Map/MapMarker.tsx
src/Sankey/SankeyLink/SankeyLink.tsx

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Update reablocks v7.13.3

---

src/Sankey/SankeyNode/SankeyNode.tsx

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Before:
https://github.com/user-attachments/assets/e6607aaf-deb8-434b-a74c-8ee5e2cfb475
After:
https://github.com/user-attachments/assets/0ae41b6f-a690-40da-9b97-a7f856e64cec

Fix tooltip blinking

---

.storybook/test-runner.ts
src/AreaChart/AreaChartSingleSeries.story.tsx
src/AreaChart/AreaSeries/Area.tsx
src/BarChart/BarSeries/Bar.tsx
src/BarChart/BarSeries/MarimekkoBarSeries.tsx
src/BarChart/BarSeries/StackedBarSeries.tsx
src/BarChart/BarSeries/StackedNormalizedBarSeries.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx
src/RadialBarChart/RadialBarSeries/RadialBar.tsx
src/Sparkline/AreaSparklineChart.tsx
src/Sparkline/SonarChart.tsx
src/VennDiagram/VennArc.tsx
src/common/Gradient/Gradient.tsx

```
[ ] Bugfix
[ ] Feature
```
Issue Number: GOOD-352
```
[ ] Yes
[x] No
```

Gradient migration

---

src/AreaChart/AreaSeries/AreaSeries.tsx
src/AreaChart/AreaSeries/StackedNormalizedAreaSeries.tsx
src/BarChart/BarSeries/BarSeries.tsx
src/BarChart/BarSeries/HistogramBarSeries.tsx
src/BarChart/BarSeries/MarimekkoBarSeries.tsx
src/BarChart/BarSeries/StackedNormalizedBarSeries.tsx
src/BubbleChart/Bubble.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx
src/Heatmap/CalendarHeatmap.tsx
src/Heatmap/HeatmapCalendar.story.tsx
src/Heatmap/HeatmapSeries/HeatmapCell.tsx
src/LinearGauge/LinearGaugeBar.tsx
src/PieChart/PieArcSeries/PieArc.tsx
src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx
src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx
src/RadialGauge/RadialGaugeSeries/RadialGaugeArc.tsx
src/RadialGauge/RadialGaugeSeries/RadialGaugeStackedArc.tsx
src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx
src/ScatterPlot/ScatterSeries/ScatterPoint.tsx
src/Sparkline/SonarChart.tsx
src/SunburstChart/SunburstArc.tsx
src/TreeMap/TreeMapRect.tsx
src/VennDiagram/VennArc.tsx
src/common/Tooltip/ChartTooltip.tsx
src/common/Tooltip/TooltipArea.tsx

```
[ ] Bugfix
[ ] Feature
```
Issue Number: GOOD-354
```
[ ] Yes
[ ] No
```

GOOD-354 Tooltip migration

---

src/AreaChart/AreaSeries/AreaSeries.tsx
src/AreaChart/AreaSeries/StackedNormalizedAreaSeries.tsx
src/BarChart/BarSeries/BarSeries.tsx
src/BarChart/BarSeries/HistogramBarSeries.tsx
src/BarChart/BarSeries/MarimekkoBarSeries.tsx
src/BarChart/BarSeries/StackedNormalizedBarSeries.tsx
src/BubbleChart/Bubble.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx
src/Heatmap/CalendarHeatmap.tsx
src/Heatmap/HeatmapCalendar.story.tsx
src/Heatmap/HeatmapSeries/HeatmapCell.tsx
src/LinearGauge/LinearGaugeBar.tsx
src/Meter/Meter.tsx
src/Meter/MeterColumn.tsx
src/PieChart/PieArcSeries/PieArc.tsx
src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx
src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx
src/RadialGauge/RadialGaugeSeries/RadialGaugeArc.tsx
src/RadialGauge/RadialGaugeSeries/RadialGaugeStackedArc.tsx
src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx
src/ScatterPlot/ScatterSeries/ScatterPoint.tsx
src/Sparkline/SonarChart.tsx
src/SunburstChart/SunburstArc.tsx
src/TreeMap/TreeMapRect.tsx
src/VennDiagram/VennArc.tsx
src/common/Tooltip/ChartTooltip.tsx
src/common/Tooltip/TooltipArea.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

GOOD-368, GOOD-354 Meter migration and Tooltip refactoring

---

src/RadialBarChart/RadialBarChart.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Remove default props from RadialBarChart components

---

src/Sankey/Sankey.story.tsx
src/Sankey/Sankey.tsx
src/Sankey/SankeyLabel/SankeyLabel.tsx
src/Sankey/SankeyNode/SankeyNode.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

GOOD-375: Sankey migration

---

src/AreaChart/AreaSeries/Area.tsx
src/BarChart/BarSeries/Bar.tsx
src/BarChart/BarSeries/MarimekkoBarSeries.tsx
src/BarChart/BarSeries/StackedBarSeries.tsx
src/BarChart/BarSeries/StackedNormalizedBarSeries.tsx
src/FunnelChart/FunnelSeries/FunnelArc.tsx
src/RadialBarChart/RadialBarSeries/RadialBar.tsx
src/Sparkline/AreaSparklineChart.tsx
src/Sparkline/SonarChart.tsx
src/VennDiagram/VennArc.tsx
src/common/Gradient/Gradient.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

GOOD-352: Gradient - remove unnecessary code

---

src/ScatterPlot/ScatterPlot.tsx
src/ScatterPlot/ScatterSeries/ScatterSeries.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Remove default props from ScatterPlot and ScatterSeries components

---

src/Sparkline/AreaSparklineChart.tsx
src/Sparkline/BarSparklineChart.tsx
src/Sparkline/SparklineChart.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Remove default props from Sparkline components

---

src/common/Count/Count.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Remove default props from Count component

---

src/SunburstChart/SunburstArc.tsx
src/SunburstChart/SunburstChart.tsx
src/SunburstChart/SunburstSeries.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

GOOD-378 SunburstChart migration

---

src/TreeMap/TreeMap.tsx
src/TreeMap/TreeMapLabel.tsx
src/TreeMap/TreeMapRect.tsx
src/TreeMap/TreeMapSeries.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

GOOD-379 TreeMap migration

---

src/common/ZoomPan/ChartZoomPan.tsx
src/common/ZoomPan/ZoomPan.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Remove default props from ZoomPan and ChartZoomPan components

---

src/Sankey/SankeyLink/SankeyLink.tsx
src/common/Gestures/Move.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Gestures Move migration

---

blocks/AreaChartBlocksDarkMedium.story.tsx
blocks/__snapshots__/AreaChartBlocksDarkMedium.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Area Chart Dark Medium block story update

---

blocks/AreaChartBlocksDarkXSmall.story.tsx
blocks/__snapshots__/AreaChartBlocksDarkXSmall.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Area Chart Dark X-Small block story update

---

blocks/AreaChartBlocksLightMedium.story.tsx
blocks/__snapshots__/AreaChartBlocksLightMedium.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Area Chart Light Medium block story update

---

blocks/AreaChartBlocksLightSmall.story.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Area Chart Light Small block story update

---

blocks/AreaChartBlocksLightXSmall.story.tsx
blocks/__snapshots__/AreaChartBlocksLightXSmall.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

Area Chart Light XSmall block story update

---

blocks/BarChartBlocksDarkLarge.story.tsx
blocks/__snapshots__/BarChartBlocksDarkLarge.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```

Bar Chart Dark Large block story update

---

blocks/BarChartBlocksDarkMedium.story.tsx
blocks/__snapshots__/BarChartBlocksDarkMedium.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Bar Chart Dark Medium block story update

---

blocks/BarChartBlocksDarkSmall.story.tsx
blocks/__snapshots__/BarChartBlocksDarkSmall.story.tsx.snap

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Bar Chart Dark Small block story update

---

package-lock.json
package.json
src/WordCloud/WordCloud.story.tsx
src/WordCloud/WordCloud.tsx
src/WordCloud/WordCloudLabel.module.css
src/WordCloud/WordCloudLabel.tsx
src/WordCloud/index.ts

This PR:
- Adds a new word cloud component

Word Cloud

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
update Motion
Issue Number: GOOD-564
```
[ ] Yes
[x] No
```

GOOD-564 update Motion

---

src/AreaChart/AreaSeries/Area.tsx

```
[ ] Bugfix
[x] Feature
```
Currently I can't get click or mouse event from Area as pointer events hardcoded to "none"
Added ability to change pointer events to have ability to disable events for Area
```
[ ] Yes
[x] No
```

Add ability to change pointer event for Area

---

src/PieChart/PieArcSeries/PieArc.tsx

```
[ ] Bugfix
[x] Feature
```
No way to pass custom styles of the path to PieArc component
Add ability to pass custom styles of the path to PieArc component
```
[ ] Yes
[x] No
```

Add ability to pass custom styles of the path to PieArc component

---

src/ScatterPlot/ScatterSeries/ScatterSeries.tsx

```
[x] Bugfix
[ ] Feature
```
Issue Number: #219 
```
[ ] Yes
[x] No
```

Fix generating key for ScatterSeries points
